services:
  - type: web
    name: STM-Backend
    env: node
    region: singapore
    plan: free
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: node dist/main
    healthCheckPath: /health
    envVars:
      - key: NODE_VERSION
        value: 20